---
# This playbook deploys a simple MongoDB server. 

- hosts: mongodb-servers 
  user: jcarpent
  sudo: True

  vars:
    dbpath: /var/lib/mongo
    mongod_port: 27017

  roles:
    - iptables
    - mongodb
