---
- name: disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: remove firewalld
  yum: name=firewalld state=absent

- name: install iptables
  yum: name=iptables-services state=present

- name: run iptables
  service: name=iptables state=started enabled=yes

- name: Create the iptables file
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables
